apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://172.19.0.1:9090
    isDefault: true
    editable: false
  - name: Rahil Postgres
    type: postgres
    uid: rahil-postgres
    access: proxy
    url: rahil-gallery-db:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: rahil_gallery
      sslmode: disable
      postgresVersion: 1600
    editable: false
